version: "3.9"

services:
  poll-db:
    container_name: poll-db
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - djangonetwork
  poll-web:
    container_name: poll-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/workspace
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - poll-db
    networks:
      - djangonetwork
      
volumes:
  postgres:

networks:
      djangonetwork:
          driver: bridge